# Generated by Django 5.0.6 on 2024-07-12 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='follower',
            field=models.ManyToManyField(related_name='followed_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
