# Generated by Django 5.0.6 on 2024-07-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='only_staff_post',
            field=models.BooleanField(default=True),
        ),
    ]
