# Generated by Django 5.0.6 on 2024-07-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_only_staff_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followed_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='moderated_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
